apiVersion: v1
kind: Service
metadata:
  name: tetris-app
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: tetris
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
spec:
  selector:
    matchLabels:
      app: tetris-app
  strategy: 
    type: Recreate
    spec:
      containers:
      - name: tetris-app
        image: uzyexe/tetris:latest
        ports:
        - containerPort: 80